### ISSUE TITLE
Libraries not found

### ISSUE THREAD

**Issue by rehno-lindeque** [OpenBCI/Ganglion_Hardware_Design_Files#4]
Hi, upon opening the schematic in kicad I get some missing library links from @biomurph's personal library.

> The following libraries were not found:
> 
> /Users/biomurph/Documents/KiCad/library/OpenBCI

**Comment by biomurph** [comment]
You need to create a new path for the libraries.
In KiCAD, go to Preferences > Configure Paths
Then point to the OpenBCI_KiCad_librariy_files folder.
